### ISSUE TITLE
facciamo un file per ogni classe?

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/GiocoIntrigante#1]
facciamo un file per ogni classe?

**Comment by lucifero55** [comment]
quindi un file "Guerriero", "Ladro","Mago"?

**Comment by FabioZTessitore** [comment]
Non solo. Ogni classe un file

Il venerdì 12 febbraio 2016, lucifero55 <notifications@github.com> ha
scritto:

**Comment by lucifero55** [comment]
creati, ma non so come si faccia su python a collegare i file tra di loro (non so neanche se .py sia l'estensione giusta :P)
